#pragma once
#include "Engine/Systems/Renderer/RenderGraph/GraphReadback.h"
#include "Engine/Systems/Renderer/RenderGraph/RenderGraph.h"

namespace Swim::Render
{
	// Graph-scheduled transfer helpers. Each adds one Transfer-role pass on the
	// graph's queue; staging comes from the executor's arenas and every barrier is
	// generated by the graph. A copy covering the whole destination buffer or
	// texture subresource is an initializing Write; any narrower copy is a
	// ReadWrite that preserves the rest and therefore needs initialized contents.
	// Buffer copies need nonempty in-bounds ranges. Texture copies are tightly packed,
	// single-subresource, uncompressed color transfers with power-of-two texels.

	GraphPass AddBufferUpload(RenderGraph& graph, std::string_view name, std::span<const std::byte> data, GraphBuffer destination,
		std::uint64_t destinationOffset = 0);
	GraphPass AddBufferUpload(RenderGraph& graph, std::string_view name, std::uint64_t size, GraphUploadWriter writer,
		GraphBuffer destination, std::uint64_t destinationOffset = 0);
	// region.BufferOffset is ignored; the staging suballocation supplies it.
	GraphPass AddTextureUpload(RenderGraph& graph, std::string_view name, std::span<const std::byte> data, GraphTexture destination,
		const Rhi::BufferTextureCopyRegion& region);
	GraphReadback AddBufferReadback(
		RenderGraph& graph, std::string_view name, GraphBuffer source, std::uint64_t sourceOffset, std::uint64_t size);
	GraphReadback AddTextureReadback(
		RenderGraph& graph, std::string_view name, GraphTexture source, const Rhi::BufferTextureCopyRegion& region);
	// Tightly packed byte count for one texture copy region.
	std::uint64_t GetTextureCopyBytes(const Rhi::TextureDesc& texture, const Rhi::BufferTextureCopyRegion& region);
} // namespace Swim::Render
